### ISSUE TITLE
Scrolling Has Problems [Parent Issue]

### ISSUE THREAD

**Issue by cjwirth** [cjwirth/RichEditorView#127]
There have been issues with scrolling since the beginning. This issue is basically just the "megathread" of scrolling issues.

- [ ] [Extra scrolling space in editor](https://github.com/cjwirth/RichEditorView/issues/76)
- [ ] [Editor does not scroll when cursor is placed offscreen](https://github.com/cjwirth/RichEditorView/issues/77)
- [ ] [scrolling issue if keyboard shown](https://github.com/cjwirth/RichEditorView/issues/79)

**Comment by hansemannn** [comment]
Interested in this as well! I am wonder how people currently workaround this issue.

**Comment by adeelilyas81** [comment]
I am facing the same issue as view got bigger and bigger and go beyond the screen size hiding every other control on the screen. can we fix this view so If someone wants to see the text he/she can scroll within the specified height rather than the expanded height violating all the controls visibility

**Comment by meetdoshi1** [comment]
I am also facing same issue, did anyone got solution?

**Comment by qhu91it** [comment]
I am also facing same issue when implement for SwiftUI, after debug I see WKWebview automatic add adjustedContentInset to the ScrollView when keyboard open
![WKWebview-adjustedContentInset-debug](https://user-images.githubusercontent.com/5744633/135754300-7b76d351-e844-4298-882b-3744340a7512.png)
So I disable it like that.
```
private func setup() {
    ...
    let notificationCenter = NotificationCenter.default()
    notificationCenter.removeObserver(self.webView, name: UIResponder.keyboardWillChangeFrameNotification, object: nil)
    notificationCenter.removeObserver(self.webView, name: UIResponder.keyboardWillShowNotification, object: nil)
    notificationCenter.removeObserver(self.webView, name: UIResponder.keyboardWillHideNotification, object: nil)
}
```
